# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Variables
export SSH_PUBLIC=$HOME/.ssh/id_rsa.pub

export GOPATH=/opt/src/go

export LOCALPATH_FILE=$HOME/.dotfiles/etc/localpath
export LOCAL_PATHS=$(cat $LOCALPATH_FILE | /opt/local/bin/envsubst | xargs | tr " " :)
export ETC_PATH=$(cat /etc/paths | xargs | tr " " :)

export PATH=$LOCAL_PATHS:$ETC_PATH

export EDITOR='atom --wait'

fpath=(~/.dotfiles/lib $fpath)
#autoload all of our local functions
autoload -- ~/.dotfiles/lib/[^_]*(:t)

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ls='ls --literal --color=auto --human-readable'
alias setfile='SetFile'

alias sport='sudo /opt/local/bin/port -ucpv'
alias psx='ps -axwwr -o pid,user,%cpu,%mem,rss,state,start,command'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# OPAM configuration
. /Users/meander/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# PerlBrew configuration
source ~/.perl5/etc/bashrc
perlbrew use 5.24.0

# PYENV configuration
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "/Users/meander/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/meander/.sdkman/bin/sdkman-init.sh"

# RVM configuration
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# The next line updates PATH for the Google Cloud SDK.
source '/opt/google/cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/opt/google/cloud-sdk/completion.zsh.inc'

# iTerm2 Shell Integration for ZSH
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
