# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Tell ZSH where to look for custom plugins
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

# Variables
export SSH_PUBLIC=$HOME/.ssh/id_rsa.pub

export GOPATH=/opt/go

export LOCALPATH_FILE=$HOME/.dotfiles/etc/localpath
export LOCAL_PATHS=$(cat $LOCALPATH_FILE | /opt/local/bin/envsubst | xargs | tr " " :)
export ETC_PATH=$(cat /etc/paths | xargs | tr " " :)

export PATH=$LOCAL_PATHS:$ETC_PATH

export EDITOR='atom --wait'

fpath=(~/.dotfiles/lib $fpath)
#autoload all of our local functions
autoload -- ~/.dotfiles/lib/[^_]*(:t)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git emer)

source $ZSH/oh-my-zsh.sh

# OPAM configuration
. /Users/meander/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# PerlBrew configuration
source ~/.perl5/etc/bashrc
#perlbrew use 5.24.0

# PYENV configuration
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# swiftenv configuration
#export SWIFTENV_ROOT="$HOME/.swiftenv"
#export PATH="$SWIFTENV_ROOT/bin:$PATH"
#eval "$(swiftenv init -)"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "/Users/meander/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/meander/.sdkman/bin/sdkman-init.sh"

# RVM configuration
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# The next line updates PATH for the Google Cloud SDK.
source '/opt/google/cloud-sdk/path.zsh.inc'

# Shell command completion
source '/opt/google/cloud-sdk/completion.zsh.inc'
#source '/Users/meander/.pyenv/shims/aws_zsh_completer.sh'

# iTerm2 Shell Integration for ZSH
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# aliases
source "${HOME}/.dotfiles/zsh/zalias"

# Added by Krypton
export GPG_TTY=$(tty)

# function powerline_precmd() {
#     PS1="$(powerline-shell --shell zsh $?)"
# }
#
# function install_powerline_precmd() {
#   for s in "${precmd_functions[@]}"; do
#     if [ "$s" = "powerline_precmd" ]; then
#       return
#     fi
#   done
#   precmd_functions+=(powerline_precmd)
# }
#
# if [ "$TERM" != "linux" ]; then
#     install_powerline_precmd
# fi
