# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Variables
export SSH_PUBLIC=$HOME/.ssh/id_rsa.pub

export GOPATH=/opt/src/go

export LOCALPATH_FILE=$HOME/.dotfiles/etc/localpath
export LOCAL_PATHS=$(cat $LOCALPATH_FILE | /opt/local/bin/envsubst | xargs | tr " " :)
export ETC_PATH=$(cat /etc/paths | xargs | tr " " :)

export PATH=$LOCAL_PATHS:$ETC_PATH

export EDITOR='atom --wait'

fpath=(~/.dotfiles/lib $fpath)
#autoload all of our local functions
autoload -- ~/.dotfiles/lib/[^_]*(:t)

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias sport='sudo /opt/local/bin/port -ucpv'

alias setfile='SetFile'
alias firefox='/Applications/Firefox.app/Contents/MacOS/firefox-bin'
alias psx='ps -axwwr -o pid,user,%cpu,%mem,rss,state,start,command'
alias unsafe_chrome='open /Applications/Google\ Chrome.app/ --args --allow-file-access-from-files -–disable-web-security'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
unalias ls; alias ls='ls --literal --color=auto --human-readable'
alias setfile='SetFile'

alias sport='sudo /opt/local/bin/port -ucpv'
alias firefox='/Applications/Firefox.app/Contents/MacOS/firefox-bin'
alias psx='ps -axwwr -o pid,user,%cpu,%mem,rss,state,start,command'
alias unsafe_chrome='open /Applications/Google\ Chrome.app/ --args --allow-file-access-from-files -–disable-web-security'

# powerline-shell
function powerline_precmd() {
    PS1="$(~/.dotfiles/powerline-shell.py $? --shell zsh 2> /dev/null)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

# OPAM configuration
. /Users/meander/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# PerlBrew configuration
source ~/.perl5/etc/bashrc
perlbrew use 5.22.0

# PYENV configuration
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# RVM

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "/Users/meander/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/meander/.sdkman/bin/sdkman-init.sh"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
